// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrnbif5w_YkSii_DO0PL7MmWdKyCGO3g',
    appId: '1:606488248254:web:4a22fd74241ff158f303ef',
    messagingSenderId: '606488248254',
    projectId: 'final1-513c6',
    authDomain: 'final1-513c6.firebaseapp.com',
    databaseURL: 'https://final1-513c6-default-rtdb.firebaseio.com',
    storageBucket: 'final1-513c6.firebasestorage.app',
    measurementId: 'G-BY0JF70Q8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUhKZwm7ZmB6NwUJXFTg964RyPDyzhUM',
    appId: '1:606488248254:android:20e63a69122fbafef303ef',
    messagingSenderId: '606488248254',
    projectId: 'final1-513c6',
    databaseURL: 'https://final1-513c6-default-rtdb.firebaseio.com',
    storageBucket: 'final1-513c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXTcdJuHnAlTRAV_Tniy852kdhTlCbX4',
    appId: '1:606488248254:ios:bc063b7fb717e748f303ef',
    messagingSenderId: '606488248254',
    projectId: 'final1-513c6',
    databaseURL: 'https://final1-513c6-default-rtdb.firebaseio.com',
    storageBucket: 'final1-513c6.firebasestorage.app',
    iosBundleId: 'com.example.final2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLXTcdJuHnAlTRAV_Tniy852kdhTlCbX4',
    appId: '1:606488248254:ios:bc063b7fb717e748f303ef',
    messagingSenderId: '606488248254',
    projectId: 'final1-513c6',
    databaseURL: 'https://final1-513c6-default-rtdb.firebaseio.com',
    storageBucket: 'final1-513c6.firebasestorage.app',
    iosBundleId: 'com.example.final2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZrnbif5w_YkSii_DO0PL7MmWdKyCGO3g',
    appId: '1:606488248254:web:7a4f1099658636b3f303ef',
    messagingSenderId: '606488248254',
    projectId: 'final1-513c6',
    authDomain: 'final1-513c6.firebaseapp.com',
    databaseURL: 'https://final1-513c6-default-rtdb.firebaseio.com',
    storageBucket: 'final1-513c6.firebasestorage.app',
    measurementId: 'G-3Q4LG5WVKX',
  );

}